### ISSUE TITLE
Test to see if building the user-content transient is faster with wp_schedule_event

### ISSUE THREAD

**Issue by jhned** [Clark-Nikdel-Powell/WP-Admin-Command-Palette#15]
We could use [wp_schedule_event](https://codex.wordpress.org/Function_Reference/wp_schedule_event) to build the user-content transient, rather than doing it on activation. Doing it this way would make activation faster on large sites.

**Comment by jhned** [comment]
Yeah, I think this might be better-- take a look here: http://spruce.it/noise/use-wp-cron-to-trigger-asynchronous-background-tasks-in-wordpress-on-post-save-or-update/

**Comment by gwelser** [comment]
+1

**Comment by samueljmello** [comment]
The wp_schedule_event function just postpones the function for later. meaning, it will still need to be triggered by a user. Basically, instead of spanking Timmy for saving a post, you are going to spank Johnny later instead. Or possibly Timmy. Who knows?
