### ISSUE TITLE
User pages aren't added to the user-content array

### ISSUE THREAD

**Issue by jhned** [Clark-Nikdel-Powell/WP-Admin-Command-Palette#18]
Should we do this?

**Comment by jhned** [comment]
User data is pretty sensitive-- you wouldn't want an editor to be directed to somebody else's profile. Even though the editor wouldn't be able to view the profile because of capability levels, we'd need to make sure that the logged-in user has access to user profiles before adding them to the search data array.

On that note, I'm going to switch this to a 1.1 milestone.

**Comment by samueljmello** [comment]
added user data into search content when user has "edit_user" priveleges
