### ISSUE TITLE
Cut down size of search data array

### ISSUE THREAD

**Issue by jhned** [Clark-Nikdel-Powell/WP-Admin-Command-Palette#20]
We've got a lot of unused fields in the data array. For example, 'dashicon', 'target', 'action' and 'shortcut' aren't needed at all for user-content data, but including them in the array adds a lot more size to the search array.

We probably need to refactor the way that the $template is set up so that we don't run in to this problem. We can cut the $template var down to the essentials, and then add in the supplemental data on a conditional basis. Does that sound good to you guys?

**Comment by gwelser** [comment]
I agree. The base template should only have to common properties. We can add additional properties when needed.
